export const TTL_CONFIG = {
  DEFAULT_HOURS: 3,
  MIN_HOURS: 1,
  MAX_HOURS: 4,
  URGENCY_THRESHOLD_MINUTES: 30,
  SWEEP_INTERVAL_MINUTES: 5,
} as const;

export const PRIVACY_CONFIG = {
  FUZZ_RADIUS_METERS: 100,
  K_ANONYMITY_FLOOR: 8,
  INITIAL_RADIUS_KM: 4.5,
  MIN_RADIUS_KM: 1.5,
} as const;
